name: vm_lab_compose_standalone
services:
  db:
    image: postgres:latest
    container_name: postgres_db_standalone
    ports:
      - "6543:5432" # change port to avoid conflict with other services
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vm-lab
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistent storage
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql # database initialization script

  main_app:
    build: .
    container_name: main_app_standalone
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  postgres_data:
