services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vm-lab
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistent storage
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql # database initialization script

  main_app:
    build: .
    container_name: main_app
    ports:
      - "8501:8501"
    depends_on:
      - db

  support_ssh_flask:
    build: 
      context: https://github.com/isislab-unisa/alfresco-ssh.git
    container_name: support_ssh_flask
    ports:
      - "5000:5000"

  support_sftp_express:
    build:
      context: https://github.com/isislab-unisa/alfresco-sftp.git
    container_name: support_sftp_express
    ports:
      - "3000:3000"

volumes:
  postgres_data:
