# !!! IMPORTANT !!!
# If you're going to use Docker, change only (if necessary) the following variables:
# - cookie_name
# - cookie_expiry_days
# - ssh_credentials_request_format
# - sftp_credentials_request_format
# - ssh_connection_request_format
# - sftp_connection_request_format
# - vm_sharing_minimum_permissions
#
# If you're going to use the application without Docker, you can change the entire file


################################
#     DATABASE CONNECTION      #
################################
db_username = "username"
db_password = "password"
db_address = "db" # or localhost or "127.0.0.1" or an ip address
db_port = "5432"
db_name = "vm-lab"

################################
#     AUTHORIZATION COOKIE     #
################################
# !!! Important: the cookie name must not have spaces or dashes, or it will not be recognized by streamlit
cookie_name = "vm_lab_cookie"
cookie_key = "some cookie key"
cookie_expiry_days = 30

################################
#    SENSITIVE DATA CIPHER     #
################################
# Can be generated with `openssl rand -base64 32`
cipher_key = "some Fernet compliant key"

################################
#       SUPPORT MODULES        #
################################

#### Details of the modules
# SSH
ssh_module_url = "http://support_ssh_flask"
ssh_module_port = "5000"

# SFTP
sftp_module_url = "http://support_sftp_express"
sftp_module_port = "3000"

#### FIRST REQUEST (CREDENTIALS) FORMAT
# Describes the URL of the first request to send credentials
# Use these variables:
# $SSH_URL -> The ssh module URL
# $SFTP_URL -> The sftp module URL
# $SSH_PORT -> The ssh module port
# $SFTP_PORT -> The sftp module port

ssh_credentials_request_format = "$SSH_URL:$SSH_PORT/create-credentials"
sftp_credentials_request_format = "$SFTP_URL:$SFTP_PORT/api/sftp/credentials/create"

#### SECOND REQUEST (CONNECTION) FORMAT
# Describes the URL of the second request to connect
# Use these variables:
# $SSH_URL -> The ssh module URL
# $SFTP_URL -> The sftp module URL
# $SSH_PORT -> The ssh module port
# $SFTP_PORT -> The sftp module port
# $CONNECTION_ID -> The ID obtained from the first request

ssh_connection_request_format = "$SSH_URL:$SSH_PORT/?connection=$CONNECTION_ID"
sftp_connection_request_format = "$SFTP_URL:$SFTP_PORT/?connection=$CONNECTION_ID"

######################################
#       VM SHARING PERMISSIONS       #
######################################
# This represents the minimum level of authority required to access other users' VMs:
# manager -> Admins and Managers can access these VMs 
# admin -> Only Admins can access these VMs
# disabled -> No one can access these VMs

vm_sharing_minimum_permissions = "manager"